spring:
  jpa:
    hibernate:
      ddl-auto: create
    open-in-view: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/techinterview?serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true # 개발서버에 반영시 수정 금지, 61.97.190.252
    username: root
    password: 1q2w3e4r1!
